// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CrawlRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalJobsFound")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs_found");

                    b.Property<int>("TotalJobsSaved")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs_saved");

                    b.Property<int>("TotalPages")
                        .HasColumnType("integer")
                        .HasColumnName("total_pages");

                    b.HasKey("Id");

                    b.ToTable("crawl_runs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closing_date");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionSummary")
                        .HasColumnType("text")
                        .HasColumnName("description_summary");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employment_type");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Industry")
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_date");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_min");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seniority");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceJobId")
                        .HasColumnType("text")
                        .HasColumnName("source_job_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_mode");

                    b.HasKey("Id");

                    b.HasIndex("Company");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("Region");

                    b.ToTable("jobs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Company = "Koru Digital",
                            ContentHash = "hash-1",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionSummary = "React and .NET role for a junior developer.",
                            EmploymentType = "Full-time",
                            FirstSeenAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Technology",
                            LastSeenAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Wellington",
                            PostedDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Region = "Wellington",
                            SalaryMax = 78000m,
                            SalaryMin = 65000m,
                            Seniority = "Junior",
                            Source = "Seed",
                            SourceJobId = "seed-1",
                            Title = "Junior Software Developer",
                            UpdatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://example.com/jobs/junior-software-developer",
                            WorkMode = "Hybrid"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Company = "Harbour Systems",
                            ContentHash = "hash-2",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionSummary = "Senior backend role building APIs and data services.",
                            EmploymentType = "Full-time",
                            FirstSeenAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Technology",
                            LastSeenAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Auckland",
                            PostedDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Region = "Auckland",
                            SalaryMax = 150000m,
                            SalaryMin = 125000m,
                            Seniority = "Senior",
                            Source = "Seed",
                            SourceJobId = "seed-2",
                            Title = "Senior .NET Engineer",
                            UpdatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://example.com/jobs/senior-dotnet-engineer",
                            WorkMode = "Hybrid"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Company = "Southern Insights",
                            ContentHash = "hash-3",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionSummary = "Analytics role focused on SQL dashboards and reporting.",
                            EmploymentType = "Full-time",
                            FirstSeenAt = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Analytics",
                            LastSeenAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Christchurch",
                            PostedDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Region = "Canterbury",
                            SalaryMax = 95000m,
                            SalaryMin = 80000m,
                            Seniority = "Intermediate",
                            Source = "Seed",
                            SourceJobId = "seed-3",
                            Title = "Data Analyst",
                            UpdatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://example.com/jobs/data-analyst",
                            WorkMode = "On-site"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Company = "Cloud Kiwi",
                            ContentHash = "hash-4",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionSummary = "Graduate cloud role using Azure and infrastructure automation.",
                            EmploymentType = "Full-time",
                            FirstSeenAt = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Technology",
                            LastSeenAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Hamilton",
                            PostedDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Region = "Waikato",
                            SalaryMax = 72000m,
                            SalaryMin = 62000m,
                            Seniority = "Graduate",
                            Source = "Seed",
                            SourceJobId = "seed-4",
                            Title = "Graduate Cloud Engineer",
                            UpdatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://example.com/jobs/graduate-cloud-engineer",
                            WorkMode = "Remote"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Company = "Tui Labs",
                            ContentHash = "hash-5",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionSummary = "React and TypeScript contract role.",
                            EmploymentType = "Contract",
                            FirstSeenAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Technology",
                            LastSeenAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Auckland",
                            PostedDate = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Region = "Auckland",
                            SalaryMax = 115000m,
                            SalaryMin = 90000m,
                            Seniority = "Intermediate",
                            Source = "Seed",
                            SourceJobId = "seed-5",
                            Title = "Frontend Developer",
                            UpdatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://example.com/jobs/frontend-developer",
                            WorkMode = "Remote"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Company = "Health Data NZ",
                            ContentHash = "hash-6",
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescriptionSummary = "Business intelligence role using SQL and Power BI.",
                            EmploymentType = "Full-time",
                            FirstSeenAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Healthcare",
                            LastSeenAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Dunedin",
                            PostedDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Region = "Otago",
                            SalaryMax = 105000m,
                            SalaryMin = 85000m,
                            Seniority = "Intermediate",
                            Source = "Seed",
                            SourceJobId = "seed-6",
                            Title = "BI Developer",
                            UpdatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://example.com/jobs/bi-developer",
                            WorkMode = "Hybrid"
                        });
                });

            modelBuilder.Entity("Domain.Entities.JobSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_name");

                    b.Property<string>("SkillType")
                        .HasColumnType("text")
                        .HasColumnName("skill_type");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillName");

                    b.ToTable("job_skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0001-0000-0000-000000000001"),
                            Confidence = 1m,
                            JobId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SkillName = "React",
                            SkillType = "Framework"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0002-0000-0000-000000000002"),
                            Confidence = 1m,
                            JobId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SkillName = ".NET",
                            SkillType = "Framework"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0003-0000-0000-000000000003"),
                            Confidence = 1m,
                            JobId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SkillName = "TypeScript",
                            SkillType = "Language"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0004-0000-0000-000000000004"),
                            Confidence = 1m,
                            JobId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SkillName = ".NET",
                            SkillType = "Framework"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0005-0000-0000-000000000005"),
                            Confidence = 1m,
                            JobId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SkillName = "C#",
                            SkillType = "Language"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0006-0000-0000-000000000006"),
                            Confidence = 1m,
                            JobId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SkillName = "PostgreSQL",
                            SkillType = "Database"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0007-0000-0000-000000000007"),
                            Confidence = 1m,
                            JobId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SkillName = "SQL",
                            SkillType = "Database"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0008-0000-0000-000000000008"),
                            Confidence = 1m,
                            JobId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SkillName = "Power BI",
                            SkillType = "Tool"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0009-0000-0000-000000000009"),
                            Confidence = 1m,
                            JobId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SkillName = "Azure",
                            SkillType = "Cloud"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0010-0000-0000-000000000010"),
                            Confidence = 1m,
                            JobId = new Guid("44444444-4444-4444-4444-444444444444"),
                            SkillName = "Terraform",
                            SkillType = "Tool"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0011-0000-0000-000000000011"),
                            Confidence = 1m,
                            JobId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SkillName = "React",
                            SkillType = "Framework"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0012-0000-0000-000000000012"),
                            Confidence = 1m,
                            JobId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SkillName = "TypeScript",
                            SkillType = "Language"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0013-0000-0000-000000000013"),
                            Confidence = 1m,
                            JobId = new Guid("66666666-6666-6666-6666-666666666666"),
                            SkillName = "SQL",
                            SkillType = "Database"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0014-0000-0000-000000000014"),
                            Confidence = 1m,
                            JobId = new Guid("66666666-6666-6666-6666-666666666666"),
                            SkillName = "Power BI",
                            SkillType = "Tool"
                        });
                });

            modelBuilder.Entity("Domain.Entities.JobSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<int>("CrawlFrequencyMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("crawl_frequency_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("job_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-0001-0000-0000-000000000001"),
                            BaseUrl = "https://example.com/jobs",
                            CrawlFrequencyMinutes = 1440,
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Method = "Seed",
                            Name = "Seed",
                            UpdatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.RawJobPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CrawlRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_run_id");

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crawled_at");

                    b.Property<string>("Markdown")
                        .HasColumnType("text")
                        .HasColumnName("markdown");

                    b.Property<string>("RawHtml")
                        .HasColumnType("text")
                        .HasColumnName("raw_html");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CrawlRunId");

                    b.ToTable("raw_job_pages", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("Domain.Entities.Job", "Job")
                        .WithMany("Skills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Domain.Entities.RawJobPage", b =>
                {
                    b.HasOne("Domain.Entities.CrawlRun", "CrawlRun")
                        .WithMany("RawPages")
                        .HasForeignKey("CrawlRunId");

                    b.Navigation("CrawlRun");
                });

            modelBuilder.Entity("Domain.Entities.CrawlRun", b =>
                {
                    b.Navigation("RawPages");
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
