// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CrawlRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalJobsFound")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs_found");

                    b.Property<int>("TotalJobsSaved")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs_saved");

                    b.Property<int>("TotalPages")
                        .HasColumnType("integer")
                        .HasColumnName("total_pages");

                    b.HasKey("Id");

                    b.ToTable("crawl_runs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closing_date");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionSummary")
                        .HasColumnType("text")
                        .HasColumnName("description_summary");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employment_type");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("ExperienceBand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("experience_band");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Industry")
                        .HasColumnType("text")
                        .HasColumnName("industry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("MissingCrawlCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_crawl_count");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_date");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_min");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seniority");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceJobId")
                        .HasColumnType("text")
                        .HasColumnName("source_job_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_mode");

                    b.HasKey("Id");

                    b.HasIndex("Company");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("Region");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JobSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_name");

                    b.Property<string>("SkillType")
                        .HasColumnType("text")
                        .HasColumnName("skill_type");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillName");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JobSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<int>("CrawlFrequencyMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("crawl_frequency_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("LastCrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_crawled_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Parser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parser");

                    b.Property<DateTime?>("TermsCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_checked_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("job_sources", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RawJobPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CrawlRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_run_id");

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crawled_at");

                    b.Property<string>("Markdown")
                        .HasColumnType("text")
                        .HasColumnName("markdown");

                    b.Property<string>("RawHtml")
                        .HasColumnType("text")
                        .HasColumnName("raw_html");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CrawlRunId");

                    b.ToTable("raw_job_pages", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("Domain.Entities.Job", "Job")
                        .WithMany("Skills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Domain.Entities.RawJobPage", b =>
                {
                    b.HasOne("Domain.Entities.CrawlRun", "CrawlRun")
                        .WithMany("RawPages")
                        .HasForeignKey("CrawlRunId");

                    b.Navigation("CrawlRun");
                });

            modelBuilder.Entity("Domain.Entities.CrawlRun", b =>
                {
                    b.Navigation("RawPages");
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
